/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Source of truth: scraper/specs/schema.py (see scraper/specs/README.md).
 * Regenerate with:  python -m scraper.specs.export_site
 * CI check:         python scraper/scripts/check_spec_sync.py (or --check above)
 */

export interface SpecFieldMeta {
  /** Schema field name (units live in the name: `_ghz`, `_mm`, `_w`, ...). */
  name: string;
  type: "int" | "float" | "bool" | "str" | "enum" | "list_str" | "dict_int";
  unit: string | null;
  enum: string[];
  filterable: boolean;
  group: string;
  /** Short display label (Hebrew / English). */
  he: string;
  en: string;
}

/** Schema version — bump in schema.py; golden fixtures record it too. */
export const SCHEMA_VERSION = 1;

/** Ordered spec fields per category (the PDP renders exactly this order). */
export const SPEC_FIELDS: Record<string, SpecFieldMeta[]> = {
  "cpu": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "series", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "סדרה", en: "Series" },
    { name: "microarchitecture", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "ארכיטקטורה", en: "Microarchitecture" },
    { name: "core_family", type: "str", unit: null, enum: [], filterable: false, group: "core", he: "משפחת ליבות", en: "Core Family" },
    { name: "socket", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "סוקט", en: "Socket" },
    { name: "core_count", type: "int", unit: null, enum: [], filterable: true, group: "core", he: "ליבות", en: "Core Count" },
    { name: "thread_count", type: "int", unit: null, enum: [], filterable: true, group: "core", he: "נימים", en: "Thread Count" },
    { name: "base_clock_ghz", type: "float", unit: null, enum: [], filterable: false, group: "core", he: "תדר בסיס (GHz)", en: "Base Clock (GHz)" },
    { name: "boost_clock_ghz", type: "float", unit: null, enum: [], filterable: false, group: "core", he: "תדר מוגבר (GHz)", en: "Boost Clock (GHz)" },
    { name: "l2_cache_mb", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "מטמון L2 (MB)", en: "L2 Cache (MB)" },
    { name: "l3_cache_mb", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "מטמון L3 (MB)", en: "L3 Cache (MB)" },
    { name: "tdp_w", type: "int", unit: null, enum: [], filterable: true, group: "power", he: "הספק (W)", en: "TDP (W)" },
    { name: "integrated_graphics", type: "str", unit: null, enum: [], filterable: true, group: "other", he: "גרפיקה משולבת", en: "Integrated Graphics" },
    { name: "max_memory_gb", type: "int", unit: null, enum: [], filterable: false, group: "memory", he: "זיכרון מקסימלי (GB)", en: "Max Memory (GB)" },
    { name: "ecc_support", type: "bool", unit: null, enum: [], filterable: true, group: "memory", he: "תמיכת ECC", en: "ECC Support" },
    { name: "includes_cooler", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "כולל קירור", en: "Includes Cooler" },
    { name: "packaging", type: "enum", unit: null, enum: ["boxed", "tray", "bulk", "oem"], filterable: true, group: "identity", he: "אריזה", en: "Packaging" },
    { name: "lithography_nm", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "ליתוגרפיה (nm)", en: "Lithography (nm)" },
    { name: "smt", type: "bool", unit: null, enum: [], filterable: true, group: "core", he: "SMT", en: "SMT" },
    { name: "unlocked", type: "bool", unit: null, enum: [], filterable: false, group: "other", he: "לא נעול", en: "Unlocked" },
  ],
  "motherboard": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "socket", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "סוקט", en: "Socket" },
    { name: "chipset", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "ערכת שבבים", en: "Chipset" },
    { name: "form_factor", type: "enum", unit: null, enum: ["ATX", "EATX", "Micro-ATX", "Mini-ITX", "XL-ATX", "Mini-DTX", "Thin Mini-ITX", "SSI-EEB"], filterable: true, group: "physical", he: "פורמט", en: "Form Factor" },
    { name: "memory_type", type: "enum", unit: null, enum: ["DDR3", "DDR4", "DDR5"], filterable: true, group: "memory", he: "סוג זיכרון", en: "Memory Type" },
    { name: "memory_slots", type: "int", unit: null, enum: [], filterable: true, group: "memory", he: "חריצי זיכרון", en: "Memory Slots" },
    { name: "memory_max_gb", type: "int", unit: null, enum: [], filterable: false, group: "memory", he: "זיכרון מקסימלי (GB)", en: "Max Memory (GB)" },
    { name: "memory_speeds", type: "list_str", unit: null, enum: [], filterable: false, group: "memory", he: "מהירויות זיכרון", en: "Memory Speeds" },
    { name: "pcie_x16_slots", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "חריצי PCIe x16", en: "PCIe x16 Slots" },
    { name: "pcie_x1_slots", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "חריצי PCIe x1", en: "PCIe x1 Slots" },
    { name: "m2_slots", type: "list_str", unit: null, enum: [], filterable: false, group: "io", he: "חריצי M.2", en: "M.2 Slots" },
    { name: "sata_ports", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "יציאות SATA", en: "SATA Ports" },
    { name: "ethernet", type: "str", unit: null, enum: [], filterable: true, group: "io", he: "רשת", en: "Ethernet" },
    { name: "onboard_video", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "יציאות תצוגה", en: "Onboard Video" },
    { name: "wireless", type: "str", unit: null, enum: [], filterable: true, group: "io", he: "אלחוטי", en: "Wireless" },
    { name: "ecc_support", type: "bool", unit: null, enum: [], filterable: true, group: "memory", he: "תמיכת ECC", en: "ECC Support" },
    { name: "raid_support", type: "bool", unit: null, enum: [], filterable: false, group: "storage", he: "תמיכת RAID", en: "RAID Support" },
    { name: "back_connect", type: "bool", unit: null, enum: [], filterable: false, group: "io", he: "Back-Connect", en: "Back-Connect" },
    { name: "usb2_headers", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "מחברי USB 2.0", en: "USB 2.0 Headers" },
    { name: "usb32_gen1_headers", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "מחברי USB 3.2 Gen1", en: "USB 3.2 Gen1 Headers" },
    { name: "usb32_gen2_headers", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "מחברי USB 3.2 Gen2", en: "USB 3.2 Gen2 Headers" },
    { name: "usb_ports", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "יציאות USB", en: "Rear USB Ports" },
    { name: "fan_headers", type: "int", unit: null, enum: [], filterable: false, group: "io", he: "מחברי מאווררים", en: "Fan Headers" },
    { name: "audio", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "שמע", en: "Audio" },
    { name: "expansion_slots", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "חריצי הרחבה", en: "Expansion Slots" },
    { name: "vrm_phases", type: "str", unit: null, enum: [], filterable: false, group: "other", he: "שלבֵי VRM", en: "VRM Phases" },
    { name: "bios", type: "str", unit: null, enum: [], filterable: false, group: "other", he: "BIOS", en: "BIOS" },
    { name: "power_connections", type: "str", unit: null, enum: [], filterable: false, group: "power", he: "חיבורי חשמל", en: "Power Connections" },
    { name: "max_cooler_height_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "גובה קירור מקסימלי (mm)", en: "Max Cooler Height (mm)" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "memory": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "memory_type", type: "enum", unit: null, enum: ["DDR3", "DDR4", "DDR5"], filterable: true, group: "core", he: "סוג זיכרון", en: "Memory Type" },
    { name: "speed", type: "str", unit: null, enum: [], filterable: false, group: "core", he: "מהירות", en: "Speed" },
    { name: "speed_mhz", type: "int", unit: null, enum: [], filterable: true, group: "core", he: "מהירות (MHz)", en: "Speed (MHz)" },
    { name: "form_factor", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "פורמט", en: "Form Factor" },
    { name: "module_count", type: "int", unit: null, enum: [], filterable: true, group: "memory", he: "מספר מודולים", en: "Module Count" },
    { name: "module_size_gb", type: "int", unit: null, enum: [], filterable: false, group: "memory", he: "גודל מודול (GB)", en: "Module Size (GB)" },
    { name: "total_gb", type: "int", unit: null, enum: [], filterable: true, group: "memory", he: "נפח כולל (GB)", en: "Total (GB)" },
    { name: "first_word_latency_ns", type: "float", unit: null, enum: [], filterable: false, group: "core", he: "השהיה (ns)", en: "Latency (ns)" },
    { name: "cas_latency", type: "int", unit: null, enum: [], filterable: true, group: "core", he: "CAS Latency", en: "CAS Latency" },
    { name: "timing", type: "str", unit: null, enum: [], filterable: false, group: "core", he: "תזמונים", en: "Timings" },
    { name: "voltage_v", type: "float", unit: null, enum: [], filterable: false, group: "power", he: "מתח (V)", en: "Voltage (V)" },
    { name: "ecc", type: "bool", unit: null, enum: [], filterable: true, group: "memory", he: "ECC", en: "ECC" },
    { name: "registered", type: "bool", unit: null, enum: [], filterable: false, group: "memory", he: "Registered", en: "Registered" },
    { name: "heat_spreader", type: "bool", unit: null, enum: [], filterable: false, group: "physical", he: "גוף קירור", en: "Heat Spreader" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "storage": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "capacity_gb", type: "int", unit: null, enum: [], filterable: true, group: "storage", he: "נפח (GB)", en: "Capacity (GB)" },
    { name: "type", type: "enum", unit: null, enum: ["SSD", "HDD", "Hybrid"], filterable: true, group: "storage", he: "סוג כונן", en: "Type" },
    { name: "form_factor", type: "str", unit: null, enum: [], filterable: true, group: "storage", he: "פורמט", en: "Form Factor" },
    { name: "interface", type: "str", unit: null, enum: [], filterable: true, group: "storage", he: "ממשק", en: "Interface" },
    { name: "nvme", type: "bool", unit: null, enum: [], filterable: true, group: "storage", he: "NVMe", en: "NVMe" },
    { name: "pcie_gen", type: "int", unit: null, enum: [], filterable: true, group: "storage", he: "דור PCIe", en: "PCIe Gen" },
    { name: "cache_mb", type: "int", unit: null, enum: [], filterable: false, group: "storage", he: "מטמון (MB)", en: "Cache (MB)" },
    { name: "rpm", type: "int", unit: null, enum: [], filterable: true, group: "storage", he: "סל״ד", en: "RPM" },
    { name: "nand", type: "str", unit: null, enum: [], filterable: false, group: "storage", he: "סוג NAND", en: "NAND" },
    { name: "controller", type: "str", unit: null, enum: [], filterable: false, group: "storage", he: "בקר", en: "Controller" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "gpu": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "chipset", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "שבב גרפי", en: "Chipset" },
    { name: "memory_gb", type: "int", unit: null, enum: [], filterable: true, group: "memory", he: "זיכרון (GB)", en: "Memory (GB)" },
    { name: "memory_type", type: "str", unit: null, enum: [], filterable: false, group: "memory", he: "סוג זיכרון", en: "Memory Type" },
    { name: "core_clock_mhz", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "תדר ליבה (MHz)", en: "Core Clock (MHz)" },
    { name: "boost_clock_mhz", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "תדר מוגבר (MHz)", en: "Boost Clock (MHz)" },
    { name: "interface", type: "str", unit: null, enum: [], filterable: true, group: "core", he: "ממשק", en: "Interface" },
    { name: "length_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "אורך (mm)", en: "Length (mm)" },
    { name: "slot_width", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "רוחב חריצים", en: "Slot Width" },
    { name: "tdp_w", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "הספק (W)", en: "TDP (W)" },
    { name: "cooling", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "קירור", en: "Cooling" },
    { name: "fan_count", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "מספר מאווררים", en: "Fan Count" },
    { name: "external_power", type: "list_str", unit: null, enum: [], filterable: false, group: "power", he: "חיבורי חשמל", en: "External Power" },
    { name: "dp_outputs", type: "dict_int", unit: null, enum: [], filterable: false, group: "io", he: "יציאות DisplayPort", en: "DisplayPort Outputs" },
    { name: "hdmi_outputs", type: "dict_int", unit: null, enum: [], filterable: false, group: "io", he: "יציאות HDMI", en: "HDMI Outputs" },
    { name: "dvi_outputs", type: "dict_int", unit: null, enum: [], filterable: false, group: "io", he: "יציאות DVI", en: "DVI Outputs" },
    { name: "frame_sync", type: "str", unit: null, enum: [], filterable: false, group: "core", he: "סנכרון פריימים", en: "Frame Sync" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "case": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "type", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "סוג", en: "Type" },
    { name: "side_panel", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "פאנל צד", en: "Side Panel" },
    { name: "psu_included", type: "str", unit: null, enum: [], filterable: false, group: "power", he: "ספק כוח כלול", en: "PSU Included" },
    { name: "psu_shroud", type: "bool", unit: null, enum: [], filterable: false, group: "power", he: "כיסוי ספק כוח", en: "PSU Shroud" },
    { name: "mb_form_factors", type: "list_str", unit: null, enum: [], filterable: false, group: "physical", he: "פורמטים נתמכים", en: "Motherboard Form Factors" },
    { name: "max_gpu_length_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "אורך GPU מקסימלי (mm)", en: "Max GPU Length (mm)" },
    { name: "max_cooler_height_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "גובה קירור מקסימלי (mm)", en: "Max Cooler Height (mm)" },
    { name: "drive_bays_35", type: "int", unit: null, enum: [], filterable: false, group: "storage", he: "תאי 3.5 אינץ'", en: "3.5\" Bays" },
    { name: "drive_bays_25", type: "int", unit: null, enum: [], filterable: false, group: "storage", he: "תאי 2.5 אינץ'", en: "2.5\" Bays" },
    { name: "expansion_slots", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "חריצי הרחבה", en: "Expansion Slots" },
    { name: "front_usb", type: "list_str", unit: null, enum: [], filterable: false, group: "io", he: "USB קדמי", en: "Front USB" },
    { name: "fan_support", type: "dict_int", unit: null, enum: [], filterable: false, group: "physical", he: "תמיכת מאווררים", en: "Fan Support" },
    { name: "radiator_support", type: "dict_int", unit: null, enum: [], filterable: false, group: "physical", he: "תמיכת רדיאטורים", en: "Radiator Support" },
    { name: "dimensions_mm", type: "str", unit: null, enum: [], filterable: false, group: "physical", he: "ממדים (HxWxD)", en: "Dimensions (HxWxD)" },
    { name: "volume_l", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "נפח (L)", en: "Volume (L)" },
    { name: "weight_kg", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "משקל (kg)", en: "Weight (kg)" },
    { name: "fan_front", type: "str", unit: null, enum: [], filterable: false, group: "physical", he: "מאווררים קדמיים", en: "Front Fans" },
    { name: "fan_top", type: "str", unit: null, enum: [], filterable: false, group: "physical", he: "מאווררים עליונים", en: "Top Fans" },
    { name: "fan_rear", type: "str", unit: null, enum: [], filterable: false, group: "physical", he: "מאוורר אחורי", en: "Rear Fan" },
    { name: "fan_bottom", type: "str", unit: null, enum: [], filterable: false, group: "physical", he: "מאווררים תחתונים", en: "Bottom Fans" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "psu": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "type", type: "enum", unit: null, enum: ["ATX", "SFX", "SFX-L", "TFX", "Flex ATX", "Micro ATX", "Mini ITX", "1U"], filterable: true, group: "identity", he: "סוג", en: "Type" },
    { name: "wattage_w", type: "int", unit: null, enum: [], filterable: true, group: "power", he: "הספק (W)", en: "Wattage (W)" },
    { name: "efficiency", type: "enum", unit: null, enum: ["80+ White", "80+ Bronze", "80+ Silver", "80+ Gold", "80+ Platinum", "80+ Titanium"], filterable: true, group: "power", he: "יעילות", en: "Efficiency" },
    { name: "modular", type: "enum", unit: null, enum: ["no", "semi", "full"], filterable: true, group: "power", he: "מודולרי", en: "Modular" },
    { name: "length_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "אורך (mm)", en: "Length (mm)" },
    { name: "fanless", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "ללא מאוורר", en: "Fanless" },
    { name: "atx_version", type: "str", unit: null, enum: [], filterable: false, group: "power", he: "תקן ATX", en: "ATX Version" },
    { name: "atx4_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי ATX 24-pin", en: "ATX 24-pin Connectors" },
    { name: "eps8_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי EPS 8-pin", en: "EPS 8-pin Connectors" },
    { name: "pcie16_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי PCIe 16-pin", en: "PCIe 16-pin Connectors" },
    { name: "pcie12_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי PCIe 12-pin", en: "PCIe 12-pin Connectors" },
    { name: "pcie8_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי PCIe 8-pin", en: "PCIe 8-pin Connectors" },
    { name: "pcie62_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי PCIe 6+2-pin", en: "PCIe 6+2-pin Connectors" },
    { name: "pcie6_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי PCIe 6-pin", en: "PCIe 6-pin Connectors" },
    { name: "sata_connectors", type: "int", unit: null, enum: [], filterable: true, group: "power", he: "מחברי SATA", en: "SATA Connectors" },
    { name: "molex4_connectors", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "מחברי Molex", en: "Molex Connectors" },
    { name: "pcie_power_connectors", type: "str", unit: null, enum: [], filterable: false, group: "power", he: "חיבורי PCIe", en: "PCIe Power Connectors" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "case_fan": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל (mm)", en: "Size (mm)" },
    { name: "quantity", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "כמות בחבילה", en: "Quantity" },
    { name: "flow_direction", type: "enum", unit: null, enum: ["standard", "reverse"], filterable: false, group: "physical", he: "כיוון זרימה", en: "Flow Direction" },
    { name: "rpm_min", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "סל״ד מינימלי", en: "RPM Min" },
    { name: "rpm_max", type: "int", unit: null, enum: [], filterable: false, group: "core", he: "סל״ד מקסימלי", en: "RPM Max" },
    { name: "airflow_cfm", type: "float", unit: null, enum: [], filterable: false, group: "core", he: "ספיקת אוויר (CFM)", en: "Airflow (CFM)" },
    { name: "noise_db", type: "float", unit: null, enum: [], filterable: false, group: "core", he: "רעש (dB)", en: "Noise (dB)" },
    { name: "static_pressure_mmh2o", type: "float", unit: null, enum: [], filterable: false, group: "core", he: "לחץ סטטי (mmH2O)", en: "Static Pressure (mmH2O)" },
    { name: "pwm", type: "bool", unit: null, enum: [], filterable: true, group: "core", he: "PWM", en: "PWM" },
    { name: "connector", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "מחבר", en: "Connector" },
    { name: "led", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "LED" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "aio": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "water_cooled", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "קירור נוזלי", en: "Water Cooled" },
    { name: "radiator_size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל רדיאטור (mm)", en: "Radiator Size (mm)" },
    { name: "fan_size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל מאוורר (mm)", en: "Fan Size (mm)" },
    { name: "fan_count", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "מספר מאווררים", en: "Fan Count" },
    { name: "fan_rpm_min", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "סל״ד מינימלי", en: "Fan RPM Min" },
    { name: "fan_rpm_max", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "סל״ד מקסימלי", en: "Fan RPM Max" },
    { name: "noise_db", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "רעש (dB)", en: "Noise (dB)" },
    { name: "airflow_cfm", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "ספיקת אוויר (CFM)", en: "Airflow (CFM)" },
    { name: "height_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "גובה (mm)", en: "Height (mm)" },
    { name: "sockets", type: "list_str", unit: null, enum: [], filterable: true, group: "io", he: "סוקטים נתמכים", en: "Sockets" },
    { name: "tdp_w", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "פיזור חום (W)", en: "Cooling Capacity (W)" },
    { name: "fanless", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "ללא מאוורר", en: "Fanless" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "cooler_air": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "water_cooled", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "קירור נוזלי", en: "Water Cooled" },
    { name: "radiator_size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל רדיאטור (mm)", en: "Radiator Size (mm)" },
    { name: "fan_size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל מאוורר (mm)", en: "Fan Size (mm)" },
    { name: "fan_count", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "מספר מאווררים", en: "Fan Count" },
    { name: "fan_rpm_min", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "סל״ד מינימלי", en: "Fan RPM Min" },
    { name: "fan_rpm_max", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "סל״ד מקסימלי", en: "Fan RPM Max" },
    { name: "noise_db", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "רעש (dB)", en: "Noise (dB)" },
    { name: "airflow_cfm", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "ספיקת אוויר (CFM)", en: "Airflow (CFM)" },
    { name: "height_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "גובה (mm)", en: "Height (mm)" },
    { name: "sockets", type: "list_str", unit: null, enum: [], filterable: true, group: "io", he: "סוקטים נתמכים", en: "Sockets" },
    { name: "tdp_w", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "פיזור חום (W)", en: "Cooling Capacity (W)" },
    { name: "fanless", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "ללא מאוורר", en: "Fanless" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "cooling_other": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "water_cooled", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "קירור נוזלי", en: "Water Cooled" },
    { name: "radiator_size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל רדיאטור (mm)", en: "Radiator Size (mm)" },
    { name: "fan_size_mm", type: "int", unit: null, enum: [], filterable: true, group: "physical", he: "גודל מאוורר (mm)", en: "Fan Size (mm)" },
    { name: "fan_count", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "מספר מאווררים", en: "Fan Count" },
    { name: "fan_rpm_min", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "סל״ד מינימלי", en: "Fan RPM Min" },
    { name: "fan_rpm_max", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "סל״ד מקסימלי", en: "Fan RPM Max" },
    { name: "noise_db", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "רעש (dB)", en: "Noise (dB)" },
    { name: "airflow_cfm", type: "float", unit: null, enum: [], filterable: false, group: "physical", he: "ספיקת אוויר (CFM)", en: "Airflow (CFM)" },
    { name: "height_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "גובה (mm)", en: "Height (mm)" },
    { name: "sockets", type: "list_str", unit: null, enum: [], filterable: true, group: "io", he: "סוקטים נתמכים", en: "Sockets" },
    { name: "tdp_w", type: "int", unit: null, enum: [], filterable: false, group: "power", he: "פיזור חום (W)", en: "Cooling Capacity (W)" },
    { name: "fanless", type: "bool", unit: null, enum: [], filterable: true, group: "physical", he: "ללא מאוורר", en: "Fanless" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "accessories": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "accessory_type", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "סוג אביזר", en: "Accessory Type" },
    { name: "quantity", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "כמות", en: "Quantity" },
    { name: "connector", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "מחבר", en: "Connector" },
    { name: "length_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "אורך (mm)", en: "Length (mm)" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
  "other": [
    { name: "manufacturer", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "יצרן", en: "Manufacturer" },
    { name: "model", type: "str", unit: null, enum: [], filterable: false, group: "identity", he: "דגם", en: "Model" },
    { name: "part_numbers", type: "list_str", unit: null, enum: [], filterable: false, group: "identity", he: "מק״טים", en: "Part Numbers" },
    { name: "accessory_type", type: "str", unit: null, enum: [], filterable: true, group: "identity", he: "סוג אביזר", en: "Accessory Type" },
    { name: "quantity", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "כמות", en: "Quantity" },
    { name: "connector", type: "str", unit: null, enum: [], filterable: false, group: "io", he: "מחבר", en: "Connector" },
    { name: "length_mm", type: "int", unit: null, enum: [], filterable: false, group: "physical", he: "אורך (mm)", en: "Length (mm)" },
    { name: "lighting", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "תאורה", en: "Lighting" },
    { name: "color", type: "str", unit: null, enum: [], filterable: true, group: "physical", he: "צבע", en: "Color" },
  ],
};

/** Category -> filterable field names (the filter rail's allowlist). */
export const FILTERABLE_FIELDS: Record<string, string[]> = {
  "cpu": ["manufacturer", "series", "microarchitecture", "socket", "core_count", "thread_count", "tdp_w", "integrated_graphics", "ecc_support", "includes_cooler", "packaging", "smt"],
  "motherboard": ["manufacturer", "socket", "chipset", "form_factor", "memory_type", "memory_slots", "ethernet", "wireless", "ecc_support", "color"],
  "memory": ["manufacturer", "memory_type", "speed_mhz", "form_factor", "module_count", "total_gb", "cas_latency", "ecc", "lighting", "color"],
  "storage": ["manufacturer", "capacity_gb", "type", "form_factor", "interface", "nvme", "pcie_gen", "rpm", "color"],
  "gpu": ["manufacturer", "chipset", "memory_gb", "interface", "cooling", "color"],
  "case": ["manufacturer", "type", "side_panel", "max_gpu_length_mm", "lighting", "color"],
  "psu": ["manufacturer", "type", "wattage_w", "efficiency", "modular", "length_mm", "fanless", "sata_connectors", "lighting", "color"],
  "case_fan": ["manufacturer", "size_mm", "pwm", "led", "color"],
  "aio": ["manufacturer", "water_cooled", "radiator_size_mm", "fan_size_mm", "sockets", "fanless", "lighting", "color"],
  "cooler_air": ["manufacturer", "water_cooled", "radiator_size_mm", "fan_size_mm", "sockets", "fanless", "lighting", "color"],
  "cooling_other": ["manufacturer", "water_cooled", "radiator_size_mm", "fan_size_mm", "sockets", "fanless", "lighting", "color"],
  "accessories": ["manufacturer", "accessory_type", "lighting", "color"],
  "other": ["manufacturer", "accessory_type", "lighting", "color"],
};

/** Field -> label, merged into i18n ATTRIBUTE_LABELS. */
export const SPEC_LABELS: Record<string, { he: string; en: string }> = {
  "accessory_type": { he: "סוג אביזר", en: "Accessory Type" },
  "airflow_cfm": { he: "ספיקת אוויר (CFM)", en: "Airflow (CFM)" },
  "atx4_connectors": { he: "מחברי ATX 24-pin", en: "ATX 24-pin Connectors" },
  "atx_version": { he: "תקן ATX", en: "ATX Version" },
  "audio": { he: "שמע", en: "Audio" },
  "back_connect": { he: "Back-Connect", en: "Back-Connect" },
  "base_clock_ghz": { he: "תדר בסיס (GHz)", en: "Base Clock (GHz)" },
  "bios": { he: "BIOS", en: "BIOS" },
  "boost_clock_ghz": { he: "תדר מוגבר (GHz)", en: "Boost Clock (GHz)" },
  "boost_clock_mhz": { he: "תדר מוגבר (MHz)", en: "Boost Clock (MHz)" },
  "cache_mb": { he: "מטמון (MB)", en: "Cache (MB)" },
  "capacity_gb": { he: "נפח (GB)", en: "Capacity (GB)" },
  "cas_latency": { he: "CAS Latency", en: "CAS Latency" },
  "chipset": { he: "ערכת שבבים", en: "Chipset" },
  "color": { he: "צבע", en: "Color" },
  "connector": { he: "מחבר", en: "Connector" },
  "controller": { he: "בקר", en: "Controller" },
  "cooling": { he: "קירור", en: "Cooling" },
  "core_clock_mhz": { he: "תדר ליבה (MHz)", en: "Core Clock (MHz)" },
  "core_count": { he: "ליבות", en: "Core Count" },
  "core_family": { he: "משפחת ליבות", en: "Core Family" },
  "dimensions_mm": { he: "ממדים (HxWxD)", en: "Dimensions (HxWxD)" },
  "dp_outputs": { he: "יציאות DisplayPort", en: "DisplayPort Outputs" },
  "drive_bays_25": { he: "תאי 2.5 אינץ'", en: "2.5\" Bays" },
  "drive_bays_35": { he: "תאי 3.5 אינץ'", en: "3.5\" Bays" },
  "dvi_outputs": { he: "יציאות DVI", en: "DVI Outputs" },
  "ecc": { he: "ECC", en: "ECC" },
  "ecc_support": { he: "תמיכת ECC", en: "ECC Support" },
  "efficiency": { he: "יעילות", en: "Efficiency" },
  "eps8_connectors": { he: "מחברי EPS 8-pin", en: "EPS 8-pin Connectors" },
  "ethernet": { he: "רשת", en: "Ethernet" },
  "expansion_slots": { he: "חריצי הרחבה", en: "Expansion Slots" },
  "external_power": { he: "חיבורי חשמל", en: "External Power" },
  "fan_bottom": { he: "מאווררים תחתונים", en: "Bottom Fans" },
  "fan_count": { he: "מספר מאווררים", en: "Fan Count" },
  "fan_front": { he: "מאווררים קדמיים", en: "Front Fans" },
  "fan_headers": { he: "מחברי מאווררים", en: "Fan Headers" },
  "fan_rear": { he: "מאוורר אחורי", en: "Rear Fan" },
  "fan_rpm_max": { he: "סל״ד מקסימלי", en: "Fan RPM Max" },
  "fan_rpm_min": { he: "סל״ד מינימלי", en: "Fan RPM Min" },
  "fan_size_mm": { he: "גודל מאוורר (mm)", en: "Fan Size (mm)" },
  "fan_support": { he: "תמיכת מאווררים", en: "Fan Support" },
  "fan_top": { he: "מאווררים עליונים", en: "Top Fans" },
  "fanless": { he: "ללא מאוורר", en: "Fanless" },
  "first_word_latency_ns": { he: "השהיה (ns)", en: "Latency (ns)" },
  "flow_direction": { he: "כיוון זרימה", en: "Flow Direction" },
  "form_factor": { he: "פורמט", en: "Form Factor" },
  "frame_sync": { he: "סנכרון פריימים", en: "Frame Sync" },
  "front_usb": { he: "USB קדמי", en: "Front USB" },
  "hdmi_outputs": { he: "יציאות HDMI", en: "HDMI Outputs" },
  "heat_spreader": { he: "גוף קירור", en: "Heat Spreader" },
  "height_mm": { he: "גובה (mm)", en: "Height (mm)" },
  "includes_cooler": { he: "כולל קירור", en: "Includes Cooler" },
  "integrated_graphics": { he: "גרפיקה משולבת", en: "Integrated Graphics" },
  "interface": { he: "ממשק", en: "Interface" },
  "l2_cache_mb": { he: "מטמון L2 (MB)", en: "L2 Cache (MB)" },
  "l3_cache_mb": { he: "מטמון L3 (MB)", en: "L3 Cache (MB)" },
  "led": { he: "תאורה", en: "LED" },
  "length_mm": { he: "אורך (mm)", en: "Length (mm)" },
  "lighting": { he: "תאורה", en: "Lighting" },
  "lithography_nm": { he: "ליתוגרפיה (nm)", en: "Lithography (nm)" },
  "m2_slots": { he: "חריצי M.2", en: "M.2 Slots" },
  "manufacturer": { he: "יצרן", en: "Manufacturer" },
  "max_cooler_height_mm": { he: "גובה קירור מקסימלי (mm)", en: "Max Cooler Height (mm)" },
  "max_gpu_length_mm": { he: "אורך GPU מקסימלי (mm)", en: "Max GPU Length (mm)" },
  "max_memory_gb": { he: "זיכרון מקסימלי (GB)", en: "Max Memory (GB)" },
  "mb_form_factors": { he: "פורמטים נתמכים", en: "Motherboard Form Factors" },
  "memory_gb": { he: "זיכרון (GB)", en: "Memory (GB)" },
  "memory_max_gb": { he: "זיכרון מקסימלי (GB)", en: "Max Memory (GB)" },
  "memory_slots": { he: "חריצי זיכרון", en: "Memory Slots" },
  "memory_speeds": { he: "מהירויות זיכרון", en: "Memory Speeds" },
  "memory_type": { he: "סוג זיכרון", en: "Memory Type" },
  "microarchitecture": { he: "ארכיטקטורה", en: "Microarchitecture" },
  "model": { he: "דגם", en: "Model" },
  "modular": { he: "מודולרי", en: "Modular" },
  "module_count": { he: "מספר מודולים", en: "Module Count" },
  "module_size_gb": { he: "גודל מודול (GB)", en: "Module Size (GB)" },
  "molex4_connectors": { he: "מחברי Molex", en: "Molex Connectors" },
  "nand": { he: "סוג NAND", en: "NAND" },
  "noise_db": { he: "רעש (dB)", en: "Noise (dB)" },
  "nvme": { he: "NVMe", en: "NVMe" },
  "onboard_video": { he: "יציאות תצוגה", en: "Onboard Video" },
  "packaging": { he: "אריזה", en: "Packaging" },
  "part_numbers": { he: "מק״טים", en: "Part Numbers" },
  "pcie12_connectors": { he: "מחברי PCIe 12-pin", en: "PCIe 12-pin Connectors" },
  "pcie16_connectors": { he: "מחברי PCIe 16-pin", en: "PCIe 16-pin Connectors" },
  "pcie62_connectors": { he: "מחברי PCIe 6+2-pin", en: "PCIe 6+2-pin Connectors" },
  "pcie6_connectors": { he: "מחברי PCIe 6-pin", en: "PCIe 6-pin Connectors" },
  "pcie8_connectors": { he: "מחברי PCIe 8-pin", en: "PCIe 8-pin Connectors" },
  "pcie_gen": { he: "דור PCIe", en: "PCIe Gen" },
  "pcie_power_connectors": { he: "חיבורי PCIe", en: "PCIe Power Connectors" },
  "pcie_x16_slots": { he: "חריצי PCIe x16", en: "PCIe x16 Slots" },
  "pcie_x1_slots": { he: "חריצי PCIe x1", en: "PCIe x1 Slots" },
  "power_connections": { he: "חיבורי חשמל", en: "Power Connections" },
  "psu_included": { he: "ספק כוח כלול", en: "PSU Included" },
  "psu_shroud": { he: "כיסוי ספק כוח", en: "PSU Shroud" },
  "pwm": { he: "PWM", en: "PWM" },
  "quantity": { he: "כמות בחבילה", en: "Quantity" },
  "radiator_size_mm": { he: "גודל רדיאטור (mm)", en: "Radiator Size (mm)" },
  "radiator_support": { he: "תמיכת רדיאטורים", en: "Radiator Support" },
  "raid_support": { he: "תמיכת RAID", en: "RAID Support" },
  "registered": { he: "Registered", en: "Registered" },
  "rpm": { he: "סל״ד", en: "RPM" },
  "rpm_max": { he: "סל״ד מקסימלי", en: "RPM Max" },
  "rpm_min": { he: "סל״ד מינימלי", en: "RPM Min" },
  "sata_connectors": { he: "מחברי SATA", en: "SATA Connectors" },
  "sata_ports": { he: "יציאות SATA", en: "SATA Ports" },
  "series": { he: "סדרה", en: "Series" },
  "side_panel": { he: "פאנל צד", en: "Side Panel" },
  "size_mm": { he: "גודל (mm)", en: "Size (mm)" },
  "slot_width": { he: "רוחב חריצים", en: "Slot Width" },
  "smt": { he: "SMT", en: "SMT" },
  "socket": { he: "סוקט", en: "Socket" },
  "sockets": { he: "סוקטים נתמכים", en: "Sockets" },
  "speed": { he: "מהירות", en: "Speed" },
  "speed_mhz": { he: "מהירות (MHz)", en: "Speed (MHz)" },
  "static_pressure_mmh2o": { he: "לחץ סטטי (mmH2O)", en: "Static Pressure (mmH2O)" },
  "tdp_w": { he: "הספק (W)", en: "TDP (W)" },
  "thread_count": { he: "נימים", en: "Thread Count" },
  "timing": { he: "תזמונים", en: "Timings" },
  "total_gb": { he: "נפח כולל (GB)", en: "Total (GB)" },
  "type": { he: "סוג כונן", en: "Type" },
  "unlocked": { he: "לא נעול", en: "Unlocked" },
  "usb2_headers": { he: "מחברי USB 2.0", en: "USB 2.0 Headers" },
  "usb32_gen1_headers": { he: "מחברי USB 3.2 Gen1", en: "USB 3.2 Gen1 Headers" },
  "usb32_gen2_headers": { he: "מחברי USB 3.2 Gen2", en: "USB 3.2 Gen2 Headers" },
  "usb_ports": { he: "יציאות USB", en: "Rear USB Ports" },
  "voltage_v": { he: "מתח (V)", en: "Voltage (V)" },
  "volume_l": { he: "נפח (L)", en: "Volume (L)" },
  "vrm_phases": { he: "שלבֵי VRM", en: "VRM Phases" },
  "water_cooled": { he: "קירור נוזלי", en: "Water Cooled" },
  "wattage_w": { he: "הספק (W)", en: "Wattage (W)" },
  "weight_kg": { he: "משקל (kg)", en: "Weight (kg)" },
  "wireless": { he: "אלחוטי", en: "Wireless" },
};
